name: Deploy

on:
  workflow_dispatch:

jobs:
  netlify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create env
        run: |
          touch .env
          echo VITE_OMNICOMM_LOGIN=${{ secrets.OMNICOMM_LOGIN }} >> .env
          echo VITE_OMNICOMM_PASSWORD=${{ secrets.OMNICOMM_PASSWORD }} >> .env
          echo VITE_MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }} >> .env
          cat .env

      - name: Build app
        run: yarn build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './dist'
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
